package survey;
// Generated Feb 23, 2017 6:28:00 AM by Hibernate Tools 4.3.1



/**
 * Response generated by hbm2java
 */
public class Response  implements java.io.Serializable {


     private int responseId;
     private Question question;
     private Rating rating;
     private SurveyRespondent surveyRespondent;
     
     //new vars
     private int questionFoo;
     private int ratingFoo;
     private int surveyRespondentFoo;

    public Response() {
    }

	
    public Response(int responseId, Question question, SurveyRespondent surveyRespondent) {
        this.responseId = responseId;
        this.question = question;
        this.surveyRespondent = surveyRespondent;
    }
    public Response(int responseId, Question question, Rating rating, SurveyRespondent surveyRespondent) {
       this.responseId = responseId;
       this.question = question;
       this.rating = rating;
       this.surveyRespondent = surveyRespondent;
    }
    
    //new constrcutor 1
     public Response(Question question, Rating rating, SurveyRespondent surveyRespondent) {
       //this.responseId = responseId;
       this.question = question;
       this.rating = rating;
       this.surveyRespondent = surveyRespondent;
    }
    
    //new constructor 2
     public Response(int questionFoo, int ratingFoo, int surveyRespondentFoo) {
       //this.responseId = responseId;
       this.questionFoo = questionFoo;
       this.ratingFoo = ratingFoo;
       this.surveyRespondentFoo = surveyRespondentFoo;
    }
   
    public int getResponseId() {
        return this.responseId;
    }
    
    public void setResponseId(int responseId) {
        this.responseId = responseId;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Rating getRating() {
        return this.rating;
    }
    
    public void setRating(Rating rating) {
        this.rating = rating;
    }
    public SurveyRespondent getSurveyRespondent() {
        return this.surveyRespondent;
    }
    
    public void setSurveyRespondent(SurveyRespondent surveyRespondent) {
        this.surveyRespondent = surveyRespondent;
    }

    public int getQuestionFoo() {
        return questionFoo;
    }

    public void setQuestionFoo(int questionFoo) {
        this.questionFoo = questionFoo;
    }

    public int getRatingFoo() {
        return ratingFoo;
    }

    public void setRatingFoo(int ratingFoo) {
        this.ratingFoo = ratingFoo;
    }

    public int getSurveyRespondentFoo() {
        return surveyRespondentFoo;
    }

    public void setSurveyRespondentFoo(int surveyRespondentFoo) {
        this.surveyRespondentFoo = surveyRespondentFoo;
    }
    
    




}


